### PR TITLE
Remove Travis and add GitHub Actions.

### PR DESCRIPTION
**Pull request by jason-fox**
see: https://github.com/telefonicaid/iotagent-ul/pull/452

### CODE REVIEW

**Comment by fgalan** [comment]
Moving from Travis to git actions and increase the focus in Github for all development related tasks seems to be a good idea. However, I have one doubt (maybe due I'm a newbie with git actions :)

With travis a green or red mark appears near to the commit (and at the end, near the merge button) to show the result of the CI in the PR. However, with git actions I don't see anything similar:

imagen

Where the OK/NOK information appears now?

**Comment by fgalan** [comment]
> Where the OK/NOK information appears now?

It seem I was looking the wrong PR. I see the answer here https://github.com/telefonicaid/iotagent-ul/pull/452#issuecomment-732877937. Sorry the noise...

**Review by fgalan — APPROVED** [review]
LGTM

**Comment by fgalan** [comment]
After merging this PR, it seems test are failing in master:

imagen

Note that before this PR, last commit in September was working:

imagen

@jason-fox does this make any sense to you? Maybe some dependence has change between September and now (not too much time... but maybe)?

**Comment by jason-fox** [comment]
You have three failing tests - I guess `test/tools/mongoDBUtils.js` is the place to look at.

``text
 1) Device and configuration provisioning
       "before each" hook for "should fail with a 400 error":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/sigfox-iotagent/sigfox-iotagent/test/unit/deviceProvisioning-test.js)
```
  
```text
  2) Context Broker communication
       "before each" hook for "should answer with a 200 OK":
     Uncaught TypeError: db.dropDatabase is not a function
      at /home/runner/work/sigfox-iotagent/sigfox-iotagent/test/tools/mongoDBUtils.js:34:20
      at /home/runner/work/sigfox-iotagent/sigfox-iotagent/node_modules/mongodb/lib/utils.js:731:5
```

```text
  3) Plugin configuration test
       "before each" hook for "should use the plugin to parse the device responses":
     Uncaught TypeError: db.dropDatabase is not a function
      at /home/runner/work/sigfox-iotagent/sigfox-iotagent/test/tools/mongoDBUtils.js:34:20
      at /home/runner/work/sigfox-iotagent/sigfox-iotagent/node_modules/mongodb/lib/utils.js:731:5
```

The timeout may be related to these two, or may just need to be increased in the `package.json`

**Comment by fgalan** [comment]
I understand that the failing tests were finally fixed by PR #90 . Now master shows good health.

imagen

Thanks!
